// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Arcesoft.Chess.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GameStepsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "GameSteps.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GameSteps", "\tValidate game behavior works as expected", ProgrammingLanguage.CSharp, new string[] {
                        "Unit"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "GameSteps")))
            {
                global::Arcesoft.Chess.Tests.GameStepsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 16
#line 17
 testRunner.Given("I have a container", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
 testRunner.Given("I have a game factory", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("New game should start in correct state")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void NewGameShouldStartInCorrectState()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New game should start in correct state", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line 21
 testRunner.When("I start a new game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("I expect the game to not be over", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
 testRunner.Then("I expect the gamestate to be \'InPlay\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 24
 testRunner.Then("I expect no moves to have been made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 25
 testRunner.Then("I expect the current player is \'White\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table1.AddRow(new string[] {
                        "BR",
                        "BN",
                        "BB",
                        "BQ",
                        "BK",
                        "BB",
                        "BN",
                        "BR"});
            table1.AddRow(new string[] {
                        "BP",
                        "BP",
                        "BP",
                        "BP",
                        "BP",
                        "BP",
                        "BP",
                        "BP"});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "WP",
                        "WP",
                        "WP",
                        "WP",
                        "WP",
                        "WP",
                        "WP",
                        "WP"});
            table1.AddRow(new string[] {
                        "WR",
                        "WN",
                        "WB",
                        "WQ",
                        "WK",
                        "WB",
                        "WN",
                        "WR"});
#line 26
 testRunner.Then("I expect the current board to contain the following", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("New game should find moves for starting board")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void NewGameShouldFindMovesForStartingBoard()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New game should find moves for starting board", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line 38
 testRunner.Given("I start a new game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 39
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table2.AddRow(new string[] {
                        "A2",
                        "A3"});
            table2.AddRow(new string[] {
                        "A2",
                        "A4"});
            table2.AddRow(new string[] {
                        "B1",
                        "A3"});
            table2.AddRow(new string[] {
                        "B1",
                        "C3"});
            table2.AddRow(new string[] {
                        "B2",
                        "B3"});
            table2.AddRow(new string[] {
                        "B2",
                        "B4"});
            table2.AddRow(new string[] {
                        "C2",
                        "C3"});
            table2.AddRow(new string[] {
                        "C2",
                        "C4"});
            table2.AddRow(new string[] {
                        "D2",
                        "D3"});
            table2.AddRow(new string[] {
                        "D2",
                        "D4"});
            table2.AddRow(new string[] {
                        "E2",
                        "E3"});
            table2.AddRow(new string[] {
                        "E2",
                        "E4"});
            table2.AddRow(new string[] {
                        "F2",
                        "F3"});
            table2.AddRow(new string[] {
                        "F2",
                        "F4"});
            table2.AddRow(new string[] {
                        "G1",
                        "F3"});
            table2.AddRow(new string[] {
                        "G1",
                        "H3"});
            table2.AddRow(new string[] {
                        "G2",
                        "G3"});
            table2.AddRow(new string[] {
                        "G2",
                        "G4"});
            table2.AddRow(new string[] {
                        "H2",
                        "H3"});
            table2.AddRow(new string[] {
                        "H2",
                        "H4"});
#line 40
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for white pawns")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForWhitePawns()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for white pawns", ((string[])(null)));
#line 69
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table3.AddRow(new string[] {
                        "BK",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table3.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table3.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BP",
                        ""});
            table3.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BP",
                        "WP",
                        "BP"});
            table3.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "BP",
                        "",
                        "",
                        "",
                        ""});
            table3.AddRow(new string[] {
                        "",
                        "WP",
                        "WP",
                        "",
                        "BP",
                        "",
                        "",
                        "WK"});
            table3.AddRow(new string[] {
                        "WP",
                        "",
                        "",
                        "WP",
                        "WP",
                        "",
                        "",
                        "WP"});
            table3.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
#line 70
 testRunner.Given("I start a new game in the following state", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination",
                        "Result"});
            table4.AddRow(new string[] {
                        "A1",
                        "A2",
                        "None"});
            table4.AddRow(new string[] {
                        "F7",
                        "F5",
                        "None"});
#line 82
 testRunner.Given("I have the following move history", ((string)(null)), table4, "Given ");
#line 86
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table5.AddRow(new string[] {
                        "A2",
                        "A3"});
            table5.AddRow(new string[] {
                        "A2",
                        "A4"});
            table5.AddRow(new string[] {
                        "B3",
                        "B4"});
            table5.AddRow(new string[] {
                        "C3",
                        "C4"});
            table5.AddRow(new string[] {
                        "C3",
                        "D4"});
            table5.AddRow(new string[] {
                        "D2",
                        "D3"});
            table5.AddRow(new string[] {
                        "D2",
                        "E3"});
            table5.AddRow(new string[] {
                        "G5",
                        "F6"});
            table5.AddRow(new string[] {
                        "H3",
                        "H4"});
            table5.AddRow(new string[] {
                        "H3",
                        "G3"});
            table5.AddRow(new string[] {
                        "H3",
                        "G2"});
#line 87
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for black pawns")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForBlackPawns()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for black pawns", ((string[])(null)));
#line 107
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table6.AddRow(new string[] {
                        "BK",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table6.AddRow(new string[] {
                        "BP",
                        "BP",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table6.AddRow(new string[] {
                        "",
                        "WP",
                        "BP",
                        "BP",
                        "",
                        "",
                        "",
                        "BP"});
            table6.AddRow(new string[] {
                        "",
                        "WP",
                        "",
                        "WP",
                        "",
                        "",
                        "",
                        ""});
            table6.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BP",
                        "WP"});
            table6.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WP",
                        ""});
            table6.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table6.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WK"});
#line 108
 testRunner.Given("I start a new game in the following state", ((string)(null)), table6, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination",
                        "Result"});
            table7.AddRow(new string[] {
                        "H2",
                        "H4",
                        "None"});
#line 120
 testRunner.Given("I have the following move history", ((string)(null)), table7, "Given ");
#line 123
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table8.AddRow(new string[] {
                        "A8",
                        "B8"});
            table8.AddRow(new string[] {
                        "A7",
                        "A6"});
            table8.AddRow(new string[] {
                        "A7",
                        "A5"});
            table8.AddRow(new string[] {
                        "A7",
                        "B6"});
            table8.AddRow(new string[] {
                        "C6",
                        "B5"});
            table8.AddRow(new string[] {
                        "C6",
                        "C5"});
            table8.AddRow(new string[] {
                        "C6",
                        "D5"});
            table8.AddRow(new string[] {
                        "G4",
                        "H3"});
            table8.AddRow(new string[] {
                        "H6",
                        "H5"});
#line 124
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for white knights")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForWhiteKnights()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for white knights", ((string[])(null)));
#line 136
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table9.AddRow(new string[] {
                        "BK",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WN"});
            table9.AddRow(new string[] {
                        "BP",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BP",
                        ""});
            table9.AddRow(new string[] {
                        "",
                        "",
                        "WN",
                        "",
                        "",
                        "",
                        "WP",
                        ""});
            table9.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table9.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "BP",
                        "",
                        "",
                        "",
                        ""});
            table9.AddRow(new string[] {
                        "",
                        "WN",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table9.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WN",
                        ""});
            table9.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WK"});
#line 137
 testRunner.Given("I start a new game in the following state", ((string)(null)), table9, "Given ");
#line 147
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table10.AddRow(new string[] {
                        "B3",
                        "A5"});
            table10.AddRow(new string[] {
                        "B3",
                        "C5"});
            table10.AddRow(new string[] {
                        "B3",
                        "C1"});
            table10.AddRow(new string[] {
                        "B3",
                        "D4"});
            table10.AddRow(new string[] {
                        "B3",
                        "D2"});
            table10.AddRow(new string[] {
                        "C6",
                        "A5"});
            table10.AddRow(new string[] {
                        "C6",
                        "A7"});
            table10.AddRow(new string[] {
                        "C6",
                        "B8"});
            table10.AddRow(new string[] {
                        "C6",
                        "B4"});
            table10.AddRow(new string[] {
                        "C6",
                        "D8"});
            table10.AddRow(new string[] {
                        "C6",
                        "D4"});
            table10.AddRow(new string[] {
                        "C6",
                        "E7"});
            table10.AddRow(new string[] {
                        "C6",
                        "E5"});
            table10.AddRow(new string[] {
                        "G2",
                        "E1"});
            table10.AddRow(new string[] {
                        "G2",
                        "E3"});
            table10.AddRow(new string[] {
                        "G2",
                        "F4"});
            table10.AddRow(new string[] {
                        "G2",
                        "H4"});
            table10.AddRow(new string[] {
                        "H1",
                        "H2"});
            table10.AddRow(new string[] {
                        "H1",
                        "G1"});
            table10.AddRow(new string[] {
                        "H8",
                        "F7"});
#line 148
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for black knights")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForBlackKnights()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for black knights", ((string[])(null)));
#line 171
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table11.AddRow(new string[] {
                        "WK",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BN"});
            table11.AddRow(new string[] {
                        "WP",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table11.AddRow(new string[] {
                        "",
                        "",
                        "BN",
                        "",
                        "",
                        "",
                        "BP",
                        ""});
            table11.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WP",
                        ""});
            table11.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "WP",
                        "",
                        "",
                        "",
                        ""});
            table11.AddRow(new string[] {
                        "",
                        "BN",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table11.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BN",
                        ""});
            table11.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BK"});
#line 172
 testRunner.Given("I start a new game in the following state", ((string)(null)), table11, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination",
                        "Result"});
            table12.AddRow(new string[] {
                        "A1",
                        "A1",
                        "None"});
#line 182
 testRunner.Given("I have the following move history", ((string)(null)), table12, "Given ");
#line 185
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table13.AddRow(new string[] {
                        "B3",
                        "A5"});
            table13.AddRow(new string[] {
                        "B3",
                        "C5"});
            table13.AddRow(new string[] {
                        "B3",
                        "C1"});
            table13.AddRow(new string[] {
                        "B3",
                        "D4"});
            table13.AddRow(new string[] {
                        "B3",
                        "D2"});
            table13.AddRow(new string[] {
                        "C6",
                        "A5"});
            table13.AddRow(new string[] {
                        "C6",
                        "A7"});
            table13.AddRow(new string[] {
                        "C6",
                        "B8"});
            table13.AddRow(new string[] {
                        "C6",
                        "B4"});
            table13.AddRow(new string[] {
                        "C6",
                        "D8"});
            table13.AddRow(new string[] {
                        "C6",
                        "D4"});
            table13.AddRow(new string[] {
                        "C6",
                        "E7"});
            table13.AddRow(new string[] {
                        "C6",
                        "E5"});
            table13.AddRow(new string[] {
                        "G2",
                        "E1"});
            table13.AddRow(new string[] {
                        "G2",
                        "E3"});
            table13.AddRow(new string[] {
                        "G2",
                        "F4"});
            table13.AddRow(new string[] {
                        "G2",
                        "H4"});
            table13.AddRow(new string[] {
                        "H1",
                        "H2"});
            table13.AddRow(new string[] {
                        "H1",
                        "G1"});
            table13.AddRow(new string[] {
                        "H8",
                        "F7"});
#line 186
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table13, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for white bishops")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForWhiteBishops()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for white bishops", ((string[])(null)));
#line 209
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table14.AddRow(new string[] {
                        "WB",
                        "BK",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table14.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table14.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table14.AddRow(new string[] {
                        "",
                        "BP",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table14.AddRow(new string[] {
                        "",
                        "",
                        "WB",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table14.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "BP",
                        "",
                        "",
                        "BP"});
            table14.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "WP",
                        "",
                        "",
                        "WP"});
            table14.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WK"});
#line 210
 testRunner.Given("I start a new game in the following state", ((string)(null)), table14, "Given ");
#line 220
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table15.AddRow(new string[] {
                        "A8",
                        "B7"});
            table15.AddRow(new string[] {
                        "A8",
                        "C6"});
            table15.AddRow(new string[] {
                        "A8",
                        "D5"});
            table15.AddRow(new string[] {
                        "A8",
                        "E4"});
            table15.AddRow(new string[] {
                        "A8",
                        "F3"});
            table15.AddRow(new string[] {
                        "A8",
                        "G2"});
            table15.AddRow(new string[] {
                        "C4",
                        "B5"});
            table15.AddRow(new string[] {
                        "C4",
                        "B3"});
            table15.AddRow(new string[] {
                        "C4",
                        "A2"});
            table15.AddRow(new string[] {
                        "C4",
                        "D3"});
            table15.AddRow(new string[] {
                        "C4",
                        "D5"});
            table15.AddRow(new string[] {
                        "C4",
                        "E6"});
            table15.AddRow(new string[] {
                        "C4",
                        "F7"});
            table15.AddRow(new string[] {
                        "C4",
                        "G8"});
            table15.AddRow(new string[] {
                        "H1",
                        "G1"});
#line 221
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table15, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for black bishops")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForBlackBishops()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for black bishops", ((string[])(null)));
#line 239
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table16.AddRow(new string[] {
                        "BK",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table16.AddRow(new string[] {
                        "BP",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table16.AddRow(new string[] {
                        "WP",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table16.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table16.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "BB",
                        "",
                        "",
                        "",
                        ""});
            table16.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table16.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WP",
                        "WK",
                        ""});
            table16.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
#line 240
 testRunner.Given("I start a new game in the following state", ((string)(null)), table16, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination",
                        "Result"});
            table17.AddRow(new string[] {
                        "A1",
                        "A1",
                        "None"});
#line 250
 testRunner.Given("I have the following move history", ((string)(null)), table17, "Given ");
#line 253
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table18.AddRow(new string[] {
                        "A8",
                        "B8"});
            table18.AddRow(new string[] {
                        "D4",
                        "C5"});
            table18.AddRow(new string[] {
                        "D4",
                        "B6"});
            table18.AddRow(new string[] {
                        "D4",
                        "E3"});
            table18.AddRow(new string[] {
                        "D4",
                        "F2"});
            table18.AddRow(new string[] {
                        "D4",
                        "C3"});
            table18.AddRow(new string[] {
                        "D4",
                        "B2"});
            table18.AddRow(new string[] {
                        "D4",
                        "A1"});
            table18.AddRow(new string[] {
                        "D4",
                        "E5"});
            table18.AddRow(new string[] {
                        "D4",
                        "F6"});
            table18.AddRow(new string[] {
                        "D4",
                        "G7"});
            table18.AddRow(new string[] {
                        "D4",
                        "H8"});
#line 254
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table18, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for white rooks")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForWhiteRooks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for white rooks", ((string[])(null)));
#line 269
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table19.AddRow(new string[] {
                        "BK",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table19.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "BP",
                        "",
                        "",
                        "",
                        ""});
            table19.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table19.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "WR",
                        "",
                        "",
                        "",
                        ""});
            table19.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table19.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BP",
                        "BP"});
            table19.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "WP",
                        "",
                        "",
                        "",
                        "BP"});
            table19.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WK"});
#line 270
 testRunner.Given("I start a new game in the following state", ((string)(null)), table19, "Given ");
#line 280
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table20.AddRow(new string[] {
                        "D2",
                        "D3"});
            table20.AddRow(new string[] {
                        "D2",
                        "D4"});
            table20.AddRow(new string[] {
                        "D5",
                        "E5"});
            table20.AddRow(new string[] {
                        "D5",
                        "F5"});
            table20.AddRow(new string[] {
                        "D5",
                        "G5"});
            table20.AddRow(new string[] {
                        "D5",
                        "H5"});
            table20.AddRow(new string[] {
                        "D5",
                        "C5"});
            table20.AddRow(new string[] {
                        "D5",
                        "B5"});
            table20.AddRow(new string[] {
                        "D5",
                        "A5"});
            table20.AddRow(new string[] {
                        "D5",
                        "D6"});
            table20.AddRow(new string[] {
                        "D5",
                        "D7"});
            table20.AddRow(new string[] {
                        "D5",
                        "D4"});
            table20.AddRow(new string[] {
                        "D5",
                        "D3"});
#line 281
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table20, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for black rooks")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForBlackRooks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for black rooks", ((string[])(null)));
#line 297
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table21.AddRow(new string[] {
                        "BK",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table21.AddRow(new string[] {
                        "WP",
                        "",
                        "",
                        "",
                        "BP",
                        "",
                        "",
                        ""});
            table21.AddRow(new string[] {
                        "WP",
                        "WP",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table21.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table21.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "BR",
                        "",
                        "",
                        ""});
            table21.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table21.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table21.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "WR",
                        "",
                        "",
                        "WK"});
#line 298
 testRunner.Given("I start a new game in the following state", ((string)(null)), table21, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination",
                        "Result"});
            table22.AddRow(new string[] {
                        "A1",
                        "A1",
                        "None"});
#line 308
 testRunner.Given("I have the following move history", ((string)(null)), table22, "Given ");
#line 311
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table23.AddRow(new string[] {
                        "E4",
                        "F4"});
            table23.AddRow(new string[] {
                        "E4",
                        "G4"});
            table23.AddRow(new string[] {
                        "E4",
                        "H4"});
            table23.AddRow(new string[] {
                        "E4",
                        "D4"});
            table23.AddRow(new string[] {
                        "E4",
                        "C4"});
            table23.AddRow(new string[] {
                        "E4",
                        "B4"});
            table23.AddRow(new string[] {
                        "E4",
                        "A4"});
            table23.AddRow(new string[] {
                        "E4",
                        "E5"});
            table23.AddRow(new string[] {
                        "E4",
                        "E6"});
            table23.AddRow(new string[] {
                        "E4",
                        "E3"});
            table23.AddRow(new string[] {
                        "E4",
                        "E2"});
            table23.AddRow(new string[] {
                        "E4",
                        "E1"});
            table23.AddRow(new string[] {
                        "E7",
                        "E6"});
            table23.AddRow(new string[] {
                        "E7",
                        "E5"});
#line 312
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table23, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for white queens")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForWhiteQueens()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for white queens", ((string[])(null)));
#line 329
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table24.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BK"});
            table24.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "BP",
                        "",
                        "",
                        "",
                        ""});
            table24.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table24.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "WQ",
                        "",
                        "",
                        "",
                        ""});
            table24.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table24.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BP",
                        "BP"});
            table24.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "WP",
                        "",
                        "",
                        "",
                        "BP"});
            table24.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WK"});
#line 330
 testRunner.Given("I start a new game in the following state", ((string)(null)), table24, "Given ");
#line 340
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table25.AddRow(new string[] {
                        "D2",
                        "D3"});
            table25.AddRow(new string[] {
                        "D2",
                        "D4"});
            table25.AddRow(new string[] {
                        "D5",
                        "E5"});
            table25.AddRow(new string[] {
                        "D5",
                        "F5"});
            table25.AddRow(new string[] {
                        "D5",
                        "G5"});
            table25.AddRow(new string[] {
                        "D5",
                        "H5"});
            table25.AddRow(new string[] {
                        "D5",
                        "C5"});
            table25.AddRow(new string[] {
                        "D5",
                        "B5"});
            table25.AddRow(new string[] {
                        "D5",
                        "A5"});
            table25.AddRow(new string[] {
                        "D5",
                        "D6"});
            table25.AddRow(new string[] {
                        "D5",
                        "D7"});
            table25.AddRow(new string[] {
                        "D5",
                        "D4"});
            table25.AddRow(new string[] {
                        "D5",
                        "D3"});
            table25.AddRow(new string[] {
                        "D5",
                        "C6"});
            table25.AddRow(new string[] {
                        "D5",
                        "B7"});
            table25.AddRow(new string[] {
                        "D5",
                        "A8"});
            table25.AddRow(new string[] {
                        "D5",
                        "E4"});
            table25.AddRow(new string[] {
                        "D5",
                        "F3"});
            table25.AddRow(new string[] {
                        "D5",
                        "G2"});
            table25.AddRow(new string[] {
                        "D5",
                        "C4"});
            table25.AddRow(new string[] {
                        "D5",
                        "B3"});
            table25.AddRow(new string[] {
                        "D5",
                        "A2"});
            table25.AddRow(new string[] {
                        "D5",
                        "E6"});
            table25.AddRow(new string[] {
                        "D5",
                        "F7"});
            table25.AddRow(new string[] {
                        "D5",
                        "G8"});
#line 341
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table25, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for black queens")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForBlackQueens()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for black queens", ((string[])(null)));
#line 369
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table26.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BK"});
            table26.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "BP",
                        "",
                        "",
                        "",
                        "WP"});
            table26.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WP",
                        "WP"});
            table26.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table26.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "BQ",
                        "",
                        "",
                        "",
                        ""});
            table26.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table26.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "WP",
                        "",
                        "",
                        "",
                        ""});
            table26.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WK"});
#line 370
 testRunner.Given("I start a new game in the following state", ((string)(null)), table26, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination",
                        "Result"});
            table27.AddRow(new string[] {
                        "A1",
                        "A1",
                        "None"});
#line 380
 testRunner.Given("I have the following move history", ((string)(null)), table27, "Given ");
#line 383
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table28.AddRow(new string[] {
                        "D4",
                        "E4"});
            table28.AddRow(new string[] {
                        "D4",
                        "F4"});
            table28.AddRow(new string[] {
                        "D4",
                        "G4"});
            table28.AddRow(new string[] {
                        "D4",
                        "H4"});
            table28.AddRow(new string[] {
                        "D4",
                        "C4"});
            table28.AddRow(new string[] {
                        "D4",
                        "B4"});
            table28.AddRow(new string[] {
                        "D4",
                        "A4"});
            table28.AddRow(new string[] {
                        "D4",
                        "D5"});
            table28.AddRow(new string[] {
                        "D4",
                        "D6"});
            table28.AddRow(new string[] {
                        "D4",
                        "D3"});
            table28.AddRow(new string[] {
                        "D4",
                        "D2"});
            table28.AddRow(new string[] {
                        "D4",
                        "C5"});
            table28.AddRow(new string[] {
                        "D4",
                        "B6"});
            table28.AddRow(new string[] {
                        "D4",
                        "A7"});
            table28.AddRow(new string[] {
                        "D4",
                        "E3"});
            table28.AddRow(new string[] {
                        "D4",
                        "F2"});
            table28.AddRow(new string[] {
                        "D4",
                        "G1"});
            table28.AddRow(new string[] {
                        "D4",
                        "C3"});
            table28.AddRow(new string[] {
                        "D4",
                        "B2"});
            table28.AddRow(new string[] {
                        "D4",
                        "A1"});
            table28.AddRow(new string[] {
                        "D4",
                        "E5"});
            table28.AddRow(new string[] {
                        "D4",
                        "F6"});
            table28.AddRow(new string[] {
                        "D4",
                        "G7"});
            table28.AddRow(new string[] {
                        "D7",
                        "D6"});
            table28.AddRow(new string[] {
                        "D7",
                        "D5"});
#line 384
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table28, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for white King (no threats)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForWhiteKingNoThreats()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for white King (no threats)", ((string[])(null)));
#line 412
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table29.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table29.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table29.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table29.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "WK",
                        "",
                        "",
                        "",
                        ""});
            table29.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table29.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table29.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table29.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BK"});
#line 413
 testRunner.Given("I start a new game in the following state", ((string)(null)), table29, "Given ");
#line 423
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table30.AddRow(new string[] {
                        "D5",
                        "D6"});
            table30.AddRow(new string[] {
                        "D5",
                        "E5"});
            table30.AddRow(new string[] {
                        "D5",
                        "C4"});
            table30.AddRow(new string[] {
                        "D5",
                        "D4"});
            table30.AddRow(new string[] {
                        "D5",
                        "C5"});
            table30.AddRow(new string[] {
                        "D5",
                        "E6"});
            table30.AddRow(new string[] {
                        "D5",
                        "C6"});
            table30.AddRow(new string[] {
                        "D5",
                        "E4"});
#line 424
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table30, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for white King")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForWhiteKing()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for white King", ((string[])(null)));
#line 435
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table31.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table31.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table31.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table31.AddRow(new string[] {
                        "",
                        "",
                        "BR",
                        "WK",
                        "",
                        "WP",
                        "",
                        ""});
            table31.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table31.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table31.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table31.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "BK"});
#line 436
 testRunner.Given("I start a new game in the following state", ((string)(null)), table31, "Given ");
#line 446
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table32.AddRow(new string[] {
                        "D5",
                        "D6"});
            table32.AddRow(new string[] {
                        "D5",
                        "E5"});
            table32.AddRow(new string[] {
                        "D5",
                        "C4"});
#line 447
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table32, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for black King (no threats)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForBlackKingNoThreats()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for black King (no threats)", ((string[])(null)));
#line 453
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table33.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table33.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table33.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table33.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "BK",
                        "",
                        "",
                        "",
                        ""});
            table33.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table33.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table33.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table33.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WK"});
#line 454
 testRunner.Given("I start a new game in the following state", ((string)(null)), table33, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination",
                        "Result"});
            table34.AddRow(new string[] {
                        "A1",
                        "A1",
                        "None"});
#line 464
 testRunner.Given("I have the following move history", ((string)(null)), table34, "Given ");
#line 467
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table35.AddRow(new string[] {
                        "D5",
                        "D6"});
            table35.AddRow(new string[] {
                        "D5",
                        "E5"});
            table35.AddRow(new string[] {
                        "D5",
                        "C4"});
            table35.AddRow(new string[] {
                        "D5",
                        "D4"});
            table35.AddRow(new string[] {
                        "D5",
                        "C5"});
            table35.AddRow(new string[] {
                        "D5",
                        "E6"});
            table35.AddRow(new string[] {
                        "D5",
                        "C6"});
            table35.AddRow(new string[] {
                        "D5",
                        "E4"});
#line 468
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table35, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Find moves should find all moves for black King")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "GameSteps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Unit")]
        public virtual void FindMovesShouldFindAllMovesForBlackKing()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find moves should find all moves for black King", ((string[])(null)));
#line 479
this.ScenarioSetup(scenarioInfo);
#line 16
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "A",
                        "B",
                        "C",
                        "D",
                        "E",
                        "F",
                        "G",
                        "H"});
            table36.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table36.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table36.AddRow(new string[] {
                        "",
                        "",
                        "WB",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table36.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "BK",
                        "",
                        "",
                        "",
                        ""});
            table36.AddRow(new string[] {
                        "",
                        "",
                        "WQ",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table36.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table36.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table36.AddRow(new string[] {
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "WK"});
#line 480
 testRunner.Given("I start a new game in the following state", ((string)(null)), table36, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination",
                        "Result"});
            table37.AddRow(new string[] {
                        "A1",
                        "A1",
                        "None"});
#line 490
 testRunner.Given("I have the following move history", ((string)(null)), table37, "Given ");
#line 493
 testRunner.When("I find moves for the current game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Source",
                        "Destination"});
            table38.AddRow(new string[] {
                        "D5",
                        "D6"});
            table38.AddRow(new string[] {
                        "D5",
                        "E5"});
            table38.AddRow(new string[] {
                        "D5",
                        "C4"});
#line 494
 testRunner.Then("I expect the the moves found to contain", ((string)(null)), table38, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
